name: Send Daily WhatsApp Message

on:
  schedule:
    - cron: "0 7 * * *"  # Every day at 07:00 UTC

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Twilio
        run: pip install twilio

      - name: Run message script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          FROM_WHATSAPP_NUMBER: ${{ secrets.FROM_WHATSAPP_NUMBER }}
          SEND_TO: ${{ secrets.SEND_TO }}
        run: python whatsApp/main.py
