name: Send Daily WhatsApp Message

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # Every day at 04:00 UTC == 07:00 AM in israel

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r whatsApp/requirements.txt

      - name: Run message script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          FROM_WHATSAPP_NUMBER: ${{ secrets.FROM_WHATSAPP_NUMBER }}
          SEND_TO: ${{ secrets.SEND_TO }}
        run: python whatsApp/main.py
